// Mocks generated by Mockito 5.0.10 from annotations
// in fltr_mockito_null_safety/test/user_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:fltr_mockito_null_safety/model/user.dart' as _i4;
import 'package:fltr_mockito_null_safety/service/user_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i2.UserService {
  MockUserService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.User>> loadUserData() =>
      (super.noSuchMethod(Invocation.method(#loadUserData, []),
              returnValue: Future<List<_i4.User>>.value(<_i4.User>[]))
          as _i3.Future<List<_i4.User>>);
}
